---
# tasks file for ansible-cis-ubuntu-2204

# ------------------------------------------------------------------------------

- name: "SECTION6 | 6.1.1 | Ensure AIDE is installed"
  when:
    - cis_ubuntu2204_install_aide
    - cis_ubuntu2204_rule_6_1_1
  tags:
    - rule_6_1
    - server_l1
    - workstation_l1
  block:
    - name: "SECTION6 | 6.1.1 | Ensure AIDE is installed | use nullmailer instead of postfix if not installed"
      ansible.builtin.apt:
        name: nullmailer
        state: present
        force_apt_get: true
        install_recommends: false
      when:
        - not package_installed_postfix.rc == 0
    - name: "SECTION6 | 6.1.1 | Ensure AIDE is installed | install AIDE"
      ansible.builtin.apt:
        name:
          - aide
          - aide-common
        state: present
        force_apt_get: true
        install_recommends: false
    - name: "SECTION6 | 6.1.1 | Ensure AIDE is installed | stat AIDE DB"
      ansible.builtin.stat:
        path: /var/lib/aide/aide.db
      register: cis_stat_aide_db
      when:
        - cis_ubuntu2204_config_aide
    - name: "SECTION6 | 6.1.1 | Ensure AIDE is installed | iniz AIDE | could take time ..."
      ansible.builtin.command: /usr/sbin/aideinit
      args:
        creates: /var/lib/aide/aide.db
      when:
        - cis_ubuntu2204_config_aide
        - not cis_stat_aide_db.stat.exists
    - name: "SECTION6 | 6.1.1 | Ensure AIDE is installed | stat AIDE daily cron"
      ansible.builtin.stat:
        path: /etc/cron.daily/aide
      register: cis_stat_aide_cron
      when:
        - cis_ubuntu2204_config_aide

- name: "SECTION6 | 6.1.2 | Ensure filesystem integrity is regularly checked"
  ansible.builtin.cron:
    name: Run AIDE integrity check weekly
    cron_file: "{{ cis_ubuntu2204_aide_cron.cron_file | default('aide') }}"
    user: "{{ cis_ubuntu2204_aide_cron.cron_user | default('root') }}"
    minute: "{{ cis_ubuntu2204_aide_cron.aide_minute | default('0') }}"
    hour: "{{ cis_ubuntu2204_aide_cron.aide_hour | default('5') }}"
    day: "{{ cis_ubuntu2204_aide_cron.aide_day | default('*') }}"
    month: "{{ cis_ubuntu2204_aide_cron.aide_month | default('*') }}"
    weekday: "{{ cis_ubuntu2204_aide_cron.aide_weekday | default('0') }}"
    job: "{{ cis_ubuntu2204_aide_cron.aide_job }}"
  when:
    - cis_ubuntu2204_install_aide
    - cis_ubuntu2204_config_aide
    - cis_ubuntu2204_rule_6_1_2
    - not cis_stat_aide_cron.stat.exists
  tags:
    - rule_6_1
    - server_l1
    - workstation_l1

- name: "SECTION6 | 6.1.3 | Ensure cryptographic mechanisms are used to protect the integrity of audit tools"
  ansible.builtin.lineinfile:
    dest: /etc/aide/aide.conf
    regexp: "{{ item.reg }}"
    line: "{{ item.line }}"
    state: present
    create: true
    owner: root
    group: root
    mode: "0644"
  with_items:
    - reg: "{{ cis_ubuntu2204_regex_base_search }}\/sbin\/auditctl"
      line: "/sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512"
    - reg: "{{ cis_ubuntu2204_regex_base_search }}\/sbin\/auditd"
      line: "/sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512"
    - reg: "{{ cis_ubuntu2204_regex_base_search }}\/sbin\/ausearch"
      line: "/sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512"
    - reg: "{{ cis_ubuntu2204_regex_base_search }}\/sbin\/aureport"
      line: "/sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512"
    - reg: "{{ cis_ubuntu2204_regex_base_search }}\/sbin\/autrace"
      line: "/sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512"
    - reg: "{{ cis_ubuntu2204_regex_base_search }}\/sbin\/augenrules"
      line: "/sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512"
  when:
    - cis_ubuntu2204_install_aide
    - cis_ubuntu2204_config_aide
    - cis_ubuntu2204_rule_6_1_3
  tags:
    - rule_6_1
    - server_l1
    - workstation_l1
# ------------------------------------------------------------------------------
