---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Run role"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    cis_ubuntu2204_section1: true
    cis_ubuntu2204_section2: true
    cis_ubuntu2204_section3: true
    cis_ubuntu2204_section4: true
    cis_ubuntu2204_section5: true
    cis_ubuntu2204_section6: true
    cis_ubuntu2204_section7: true
    # -------------------------
    cis_ubuntu2204_rule_1_1_1_4: true # hfsplus
    cis_ubuntu2204_rule_1_1_1_6: true # overlayfs - IMPACT: consider the impact on containerized workloads, as disabling may severely disrupt containerization.
    cis_ubuntu2204_rule_1_1_1_7: true # squashfs - IMPACT: Snap packages utilizes squashfs as a compressed filesystem, disabling squashfs will cause Snap packages to fail.
    # -------------------------
    cis_ubuntu2204_rule_5_1_24: true
    cis_ubuntu2204_rule_5_1_24_ssh_user: root
    cis_ubuntu2204_rule_5_1_24_ssh_pub_key: "ssh-ed25519 aXdhc2hlcmVleGFtcGxlMTMzNwo= example"
    # -------------------------
    cis_ubuntu2204_rule_1_3_1_3: true # AppArmor complain mode
    cis_ubuntu2204_rule_1_3_1_4: true # AppArmor enforce mode
    # cis_ubuntu2204_apparmor_update_to_complain_profiles:
    #   - firefox
    # cis_ubuntu2204_apparmor_update_to_enforce_profiles:
    #   - firefox
    # -------------------------
    cis_ubuntu2204_set_boot_pass: false # bootloader password (disabled)
    cis_ubuntu2204_disable_boot_pass: true # bootloader password (disabled with cis_ubuntu2204_set_boot_pass)
    # -------------------------
    cis_ubuntu2204_rule_3_1_2: true # wireless service
    cis_ubuntu2204_rule_3_1_3: true # bluetooth service
    cis_ubuntu2204_rule_3_1_3_remove: true # bluetooth service
    # -------------------------
    cis_ubuntu2204_allow_gdm_gui: false
    cis_ubuntu2204_rule_1_7_3: true # Ensure GDM disable-user-list
    cis_ubuntu2204_allow_autofs: false # Disable auto mount, set to true to allow it and not disable
    cis_ubuntu2204_rule_1_1_1_9: true # Disable USB Storage, set to false to not disable
    cis_ubuntu2204_time_synchronization_service: chrony # chrony | systemd-timesyncd
    cis_ubuntu2204_time_synchronization_time_server:
      - uri: time.cloudflare.com
        config: iburst
      - uri: ntp.ubuntu.com
        config: iburst
    cis_ubuntu2204_allow_cups: false
    # -------------------------
    cis_ubuntu2204_install_aide: false
    cis_ubuntu2204_config_aide: true
    cis_ubuntu2204_aide_cron:
      cron_user: root
      cron_file: aide
      aide_job: "/usr/bin/aide.wrapper --config /etc/aide/aide.conf --check"
      aide_minute: 0
      aide_hour: 5
      aide_day: "*"
      aide_month: "*"
      aide_weekday: "*"
    # -------------------------
    cis_ubuntu2204_journald_system_max_use: 4G
    cis_ubuntu2204_journald_system_keep_free: 8G
    cis_ubuntu2204_journald_runtime_max_use: 256M
    cis_ubuntu2204_journald_runtime_keep_free: 512M
    cis_ubuntu2204_journald_max_file_sec: 1month
    # -------------------------
    cis_ubuntu2204_preferred_capturing_log_method: rsyslog
    # -------------------------
    cis_ubuntu2204_required_ipv6: true
    cis_ubuntu2204_firewall: ufw
    # -------------------------
    cis_ubuntu2204_cron_allow_users:
      - root
    cis_ubuntu2204_at_allow_users:
      - root
    # -------------------------
    cis_ubuntu2204_faillock_deny: 5
    cis_ubuntu2204_faillock_unlock_time: 900
    cis_ubuntu2204_faillock_minlen: 8
    cis_ubuntu2204_password_pass_max_days: 730 # 365
    cis_ubuntu2204_password_complexity:
      - key: "minclass"
        value: "3"
      - key: "dcredit"
        value: "-1"
      - key: "ucredit"
        value: "-1"
      - key: "ocredit"
        value: "-1"
      - key: "lcredit"
        value: "-1"
