---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu-23.04
    image: mvladislav/docker-ubuntu-systemd-sudo-ansible:23.04
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""} # /lib/systemd/systemd --system
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    cgroupns_mode: host
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: community.docker.docker
  config_options:
    defaults:
      roles_path: "$MOLECULE_PROJECT_DIRECTORY/.."
      display_skipped_hosts: true
      forks: 10
      retry_files_enabled: false
      host_key_checking: false
      callback_result_format: yaml
      timeout: 20
      poll_interval: 3
      callbacks_enabled: profile_tasks,timer
      fact_caching: jsonfile
      fact_caching_connection: ./.ansible_cache
      show_per_host_start: true
      bin_ansible_callbacks: true
    ssh_connection:
      pipelining: true
      transfer_method: smart
    connection:
      pipelining: true

verifier:
  name: ansible
