---
- name: PREPARE
  hosts: all
  gather_facts: false
  tasks:
    - name: "PREPARE | install essential packages for testing"
      ansible.builtin.apt:
        name:
          - openssh-server
          - grub-common
        state: present
        update_cache: yes

    - name: "PREPARE | install grub files for testing under docker"
      block:
        - name: "PREPARE | Ensure /boot/grub directory exists"
          ansible.builtin.file:
            name: /boot/grub
            state: directory
            mode: "0755"
          changed_when: false
        - name: "PREPARE | touch /boot/grub/grub.cfg"
          ansible.builtin.file:
            name: /boot/grub/grub.cfg
            state: touch
            mode: "0600"
          changed_when: false

        - name: "PREPARE | touch /etc/default/grub"
          ansible.builtin.file:
            name: /etc/default/grub
            state: touch
            mode: "0644"
          changed_when: false

    - name: "PREPARE | Setup CIS violation scenarios"
      block:
        - name: "PREPARE | 7.1.9 | create world-writable test file"
          ansible.builtin.file:
            path: /abc
            state: touch
            mode: "0777"

        - name: "PREPARE | 7.2.17 | set insecure permissions on root profile"
          ansible.builtin.file:
            path: /root/.profile
            mode: "0777"

        - name: "PREPARE | 7.2.1/2/4/11 | prepares to trigger some task"
          ansible.builtin.shell: |
            set -o pipefail
            # SECTION7 | 7.2.1 | Ensure accounts in /etc/passwd use shadowed passwords
            sed -e 's|^ubuntu:[^:]*:|ubuntu:abc:|' -i /etc/passwd
            # SECTION7 | 7.2.2 | Ensure /etc/shadow password fields are not empty
            sed -e 's|^ubuntu:[^:]*:|ubuntu::|' -i /etc/shadow
            # SECTION7 | 7.2.4 | Ensure shadow group is empty
            echo "shadow:x::666" >> /etc/group
            # SECTION7 | 7.2.11 | Ensure local interactive user home directories exist
            useradd abc
          args:
            executable: "/bin/bash"
          changed_when: false
          check_mode: false
          failed_when: false
