name: Report an issue
description: Report an issue.
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!

        If you have a feature or enhancement request, please use the feature request issue template
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: >-
        A clear and concise description of what you expected to happen.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What is version of application which has the issue?
      placeholder: core-
      description: >
        Can be found in ...
  - type: input
    attributes:
      label: What was the last working version of the application?
      placeholder: core-
      description: >
        If known, otherwise leave blank.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        If you don't know, you can find it in: Configuration panel -> Info.
      options:
        - OS (setup.py)
        - Container (docker)
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of device you use to interact with the application?
      description: >
        The device where you open the application and the problem pops up.
      options:
        - "OS: [e.g. linux, windows, ios]"
        - "Browser: [e.g. firefox, chrome, safari]"
        - "Smartphone: [e.g. android, ios]"

  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Example JSON snippet
      description: |
        If this issue has an example piece of JSON that can help reproducing this problem, please provide.
        This can be an piece of JSON from, e.g., a response from the API.
      render: json
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
